export interface CountryData {
  name: string;
  iso: string;
  phoneCode: string;
}

export const countries: CountryData[] = [
  { name: "Afghanistan", iso: "AF", phoneCode: "+93" },
  { name: "Albania", iso: "AL", phoneCode: "+355" },
  { name: "Algeria", iso: "DZ", phoneCode: "+213" },
  { name: "American Samoa", iso: "AS", phoneCode: "+1-684" },
  { name: "Andorra", iso: "AD", phoneCode: "+376" },
  { name: "Angola", iso: "AO", phoneCode: "+244" },
  { name: "Anguilla", iso: "AI", phoneCode: "+1-264" },
  { name: "Antarctica", iso: "AQ", phoneCode: "+672" },
  { name: "Antigua and Barbuda", iso: "AG", phoneCode: "+1-268" },
  { name: "Argentina", iso: "AR", phoneCode: "+54" },
  { name: "Armenia", iso: "AM", phoneCode: "+374" },
  { name: "Aruba", iso: "AW", phoneCode: "+297" },
  { name: "Australia", iso: "AU", phoneCode: "+61" },
  { name: "Austria", iso: "AT", phoneCode: "+43" },
  { name: "Azerbaijan", iso: "AZ", phoneCode: "+994" },
  { name: "Bahamas", iso: "BS", phoneCode: "+1-242" },
  { name: "Bahrain", iso: "BH", phoneCode: "+973" },
  { name: "Bangladesh", iso: "BD", phoneCode: "+880" },
  { name: "Barbados", iso: "BB", phoneCode: "+1-246" },
  { name: "Belarus", iso: "BY", phoneCode: "+375" },
  { name: "Belgium", iso: "BE", phoneCode: "+32" },
  { name: "Belize", iso: "BZ", phoneCode: "+501" },
  { name: "Benin", iso: "BJ", phoneCode: "+229" },
  { name: "Bermuda", iso: "BM", phoneCode: "+1-441" },
  { name: "Bhutan", iso: "BT", phoneCode: "+975" },
  { name: "Bolivia", iso: "BO", phoneCode: "+591" },
  { name: "Bosnia and Herzegovina", iso: "BA", phoneCode: "+387" },
  { name: "Botswana", iso: "BW", phoneCode: "+267" },
  { name: "Brazil", iso: "BR", phoneCode: "+55" },
  { name: "British Virgin Islands", iso: "VG", phoneCode: "+1-284" },
  { name: "Brunei", iso: "BN", phoneCode: "+673" },
  { name: "Bulgaria", iso: "BG", phoneCode: "+359" },
  { name: "Burkina Faso", iso: "BF", phoneCode: "+226" },
  { name: "Burundi", iso: "BI", phoneCode: "+257" },
  { name: "Cambodia", iso: "KH", phoneCode: "+855" },
  { name: "Cameroon", iso: "CM", phoneCode: "+237" },
  { name: "Canada", iso: "CA", phoneCode: "+1" },
  { name: "Cape Verde", iso: "CV", phoneCode: "+238" },
  { name: "Cayman Islands", iso: "KY", phoneCode: "+1-345" },
  { name: "Central African Republic", iso: "CF", phoneCode: "+236" },
  { name: "Chad", iso: "TD", phoneCode: "+235" },
  { name: "Chile", iso: "CL", phoneCode: "+56" },
  { name: "China", iso: "CN", phoneCode: "+86" },
  { name: "Christmas Island", iso: "CX", phoneCode: "+61" },
  { name: "Cocos Islands", iso: "CC", phoneCode: "+61" },
  { name: "Colombia", iso: "CO", phoneCode: "+57" },
  { name: "Comoros", iso: "KM", phoneCode: "+269" },
  { name: "Republic of the Congo", iso: "CG", phoneCode: "+242" },
  { name: "DR Congo", iso: "CD", phoneCode: "+243" },
  { name: "Cook Islands", iso: "CK", phoneCode: "+682" },
  { name: "Costa Rica", iso: "CR", phoneCode: "+506" },
  { name: "Croatia", iso: "HR", phoneCode: "+385" },
  { name: "Cuba", iso: "CU", phoneCode: "+53" },
  { name: "Curacao", iso: "CW", phoneCode: "+599" },
  { name: "Cyprus", iso: "CY", phoneCode: "+357" },
  { name: "Czech Republic", iso: "CZ", phoneCode: "+420" },
  { name: "Denmark", iso: "DK", phoneCode: "+45" },
  { name: "Djibouti", iso: "DJ", phoneCode: "+253" },
  { name: "Dominica", iso: "DM", phoneCode: "+1-767" },
  { name: "Dominican Republic", iso: "DO", phoneCode: "+1-809" },
  { name: "East Timor", iso: "TL", phoneCode: "+670" },
  { name: "Ecuador", iso: "EC", phoneCode: "+593" },
  { name: "Egypt", iso: "EG", phoneCode: "+20" },
  { name: "El Salvador", iso: "SV", phoneCode: "+503" },
  { name: "Equatorial Guinea", iso: "GQ", phoneCode: "+240" },
  { name: "Eritrea", iso: "ER", phoneCode: "+291" },
  { name: "Estonia", iso: "EE", phoneCode: "+372" },
  { name: "Ethiopia", iso: "ET", phoneCode: "+251" },
  { name: "Falkland Islands", iso: "FK", phoneCode: "+500" },
  { name: "Faroe Islands", iso: "FO", phoneCode: "+298" },
  { name: "Fiji", iso: "FJ", phoneCode: "+679" },
  { name: "Finland", iso: "FI", phoneCode: "+358" },
  { name: "France", iso: "FR", phoneCode: "+33" },
  { name: "French Polynesia", iso: "PF", phoneCode: "+689" },
  { name: "Gabon", iso: "GA", phoneCode: "+241" },
  { name: "Gambia", iso: "GM", phoneCode: "+220" },
  { name: "Georgia", iso: "GE", phoneCode: "+995" },
  { name: "Germany", iso: "DE", phoneCode: "+49" },
  { name: "Ghana", iso: "GH", phoneCode: "+233" },
  { name: "Gibraltar", iso: "GI", phoneCode: "+350" },
  { name: "Greece", iso: "GR", phoneCode: "+30" },
  { name: "Greenland", iso: "GL", phoneCode: "+299" },
  { name: "Grenada", iso: "GD", phoneCode: "+1-473" },
  { name: "Guam", iso: "GU", phoneCode: "+1-671" },
  { name: "Guatemala", iso: "GT", phoneCode: "+502" },
  { name: "Guernsey", iso: "GG", phoneCode: "+44-1481" },
  { name: "Guinea", iso: "GN", phoneCode: "+224" },
  { name: "Guinea-Bissau", iso: "GW", phoneCode: "+245" },
  { name: "Guyana", iso: "GY", phoneCode: "+592" },
  { name: "Haiti", iso: "HT", phoneCode: "+509" },
  { name: "Honduras", iso: "HN", phoneCode: "+504" },
  { name: "Hong Kong", iso: "HK", phoneCode: "+852" },
  { name: "Hungary", iso: "HU", phoneCode: "+36" },
  { name: "Iceland", iso: "IS", phoneCode: "+354" },
  { name: "India", iso: "IN", phoneCode: "+91" },
  { name: "Indonesia", iso: "ID", phoneCode: "+62" },
  { name: "Iran", iso: "IR", phoneCode: "+98" },
  { name: "Iraq", iso: "IQ", phoneCode: "+964" },
  { name: "Ireland", iso: "IE", phoneCode: "+353" },
  { name: "Israel", iso: "IL", phoneCode: "+972" },
  { name: "Italy", iso: "IT", phoneCode: "+39" },
  { name: "Ivory Coast", iso: "CI", phoneCode: "+225" },
  { name: "Jamaica", iso: "JM", phoneCode: "+1-876" },
  { name: "Japan", iso: "JP", phoneCode: "+81" },
  { name: "Jordan", iso: "JO", phoneCode: "+962" },
  { name: "Kazakhstan", iso: "KZ", phoneCode: "+7" },
  { name: "Kenya", iso: "KE", phoneCode: "+254" },
  { name: "Kiribati", iso: "KI", phoneCode: "+686" },
  { name: "Kosovo", iso: "XK", phoneCode: "+383" },
  { name: "Kuwait", iso: "KW", phoneCode: "+965" },
  { name: "Kyrgyzstan", iso: "KG", phoneCode: "+996" },
  { name: "Laos", iso: "LA", phoneCode: "+856" },
  { name: "Latvia", iso: "LV", phoneCode: "+371" },
  { name: "Lebanon", iso: "LB", phoneCode: "+961" },
  { name: "Lesotho", iso: "LS", phoneCode: "+266" },
  { name: "Liberia", iso: "LR", phoneCode: "+231" },
  { name: "Libya", iso: "LY", phoneCode: "+218" },
  { name: "Liechtenstein", iso: "LI", phoneCode: "+423" },
  { name: "Lithuania", iso: "LT", phoneCode: "+370" },
  { name: "Luxembourg", iso: "LU", phoneCode: "+352" },
  { name: "Macau", iso: "MO", phoneCode: "+853" },
  { name: "Macedonia", iso: "MK", phoneCode: "+389" },
  { name: "Madagascar", iso: "MG", phoneCode: "+261" },
  { name: "Malawi", iso: "MW", phoneCode: "+265" },
  { name: "Malaysia", iso: "MY", phoneCode: "+60" },
  { name: "Maldives", iso: "MV", phoneCode: "+960" },
  { name: "Mali", iso: "ML", phoneCode: "+223" },
  { name: "Malta", iso: "MT", phoneCode: "+356" },
  { name: "Marshall Islands", iso: "MH", phoneCode: "+692" },
  { name: "Mauritania", iso: "MR", phoneCode: "+222" },
  { name: "Mauritius", iso: "MU", phoneCode: "+230" },
  { name: "Mayotte", iso: "YT", phoneCode: "+262" },
  { name: "Mexico", iso: "MX", phoneCode: "+52" },
  { name: "Micronesia", iso: "FM", phoneCode: "+691" },
  { name: "Moldova", iso: "MD", phoneCode: "+373" },
  { name: "Monaco", iso: "MC", phoneCode: "+377" },
  { name: "Mongolia", iso: "MN", phoneCode: "+976" },
  { name: "Montenegro", iso: "ME", phoneCode: "+382" },
  { name: "Montserrat", iso: "MS", phoneCode: "+1-664" },
  { name: "Morocco", iso: "MA", phoneCode: "+212" },
  { name: "Mozambique", iso: "MZ", phoneCode: "+258" },
  { name: "Myanmar", iso: "MM", phoneCode: "+95" },
  { name: "Namibia", iso: "NA", phoneCode: "+264" },
  { name: "Nauru", iso: "NR", phoneCode: "+674" },
  { name: "Nepal", iso: "NP", phoneCode: "+977" },
  { name: "Netherlands", iso: "NL", phoneCode: "+31" },
  { name: "Netherlands Antilles", iso: "AN", phoneCode: "+599" },
  { name: "New Caledonia", iso: "NC", phoneCode: "+687" },
  { name: "New Zealand", iso: "NZ", phoneCode: "+64" },
  { name: "Nicaragua", iso: "NI", phoneCode: "+505" },
  { name: "Niger", iso: "NE", phoneCode: "+227" },
  { name: "Nigeria", iso: "NG", phoneCode: "+234" },
  { name: "Niue", iso: "NU", phoneCode: "+683" },
  { name: "Northern Mariana Islands", iso: "MP", phoneCode: "+1-670" },
  { name: "North Korea", iso: "KP", phoneCode: "+850" },
  { name: "Norway", iso: "NO", phoneCode: "+47" },
  { name: "Oman", iso: "OM", phoneCode: "+968" },
  { name: "Pakistan", iso: "PK", phoneCode: "+92" },
  { name: "Palau", iso: "PW", phoneCode: "+680" },
  { name: "Palestine", iso: "PS", phoneCode: "+970" },
  { name: "Panama", iso: "PA", phoneCode: "+507" },
  { name: "Papua New Guinea", iso: "PG", phoneCode: "+675" },
  { name: "Paraguay", iso: "PY", phoneCode: "+595" },
  { name: "Peru", iso: "PE", phoneCode: "+51" },
  { name: "Philippines", iso: "PH", phoneCode: "+63" },
  { name: "Pitcairn", iso: "PN", phoneCode: "+64" },
  { name: "Poland", iso: "PL", phoneCode: "+48" },
  { name: "Portugal", iso: "PT", phoneCode: "+351" },
  { name: "Puerto Rico", iso: "PR", phoneCode: "+1-787" },
  { name: "Qatar", iso: "QA", phoneCode: "+974" },
  { name: "Reunion", iso: "RE", phoneCode: "+262" },
  { name: "Romania", iso: "RO", phoneCode: "+40" },
  { name: "Russia", iso: "RU", phoneCode: "+7" },
  { name: "Rwanda", iso: "RW", phoneCode: "+250" },
  { name: "Samoa", iso: "WS", phoneCode: "+685" },
  { name: "San Marino", iso: "SM", phoneCode: "+378" },
  { name: "Sao Tome and Principe", iso: "ST", phoneCode: "+239" },
  { name: "Saudi Arabia", iso: "SA", phoneCode: "+966" },
  { name: "Senegal", iso: "SN", phoneCode: "+221" },
  { name: "Serbia", iso: "RS", phoneCode: "+381" },
  { name: "Seychelles", iso: "SC", phoneCode: "+248" },
  { name: "Sierra Leone", iso: "SL", phoneCode: "+232" },
  { name: "Singapore", iso: "SG", phoneCode: "+65" },
  { name: "Sint Maarten", iso: "SX", phoneCode: "+1-721" },
  { name: "Slovakia", iso: "SK", phoneCode: "+421" },
  { name: "Slovenia", iso: "SI", phoneCode: "+386" },
  { name: "Solomon Islands", iso: "SB", phoneCode: "+677" },
  { name: "Somalia", iso: "SO", phoneCode: "+252" },
  { name: "South Africa", iso: "ZA", phoneCode: "+27" },
  { name: "South Korea", iso: "KR", phoneCode: "+82" },
  { name: "South Sudan", iso: "SS", phoneCode: "+211" },
  { name: "Spain", iso: "ES", phoneCode: "+34" },
  { name: "Sri Lanka", iso: "LK", phoneCode: "+94" },
  { name: "Saint Helena", iso: "SH", phoneCode: "+290" },
  { name: "Saint Kitts and Nevis", iso: "KN", phoneCode: "+1-869" },
  { name: "Saint Lucia", iso: "LC", phoneCode: "+1-758" },
  { name: "Saint Martin", iso: "MF", phoneCode: "+590" },
  { name: "Saint Pierre and Miquelon", iso: "PM", phoneCode: "+508" },
  { name: "Saint Vincent Grenadines", iso: "VC", phoneCode: "+1-784" },
  { name: "Sudan", iso: "SD", phoneCode: "+249" },
  { name: "Suriname", iso: "SR", phoneCode: "+597" },
  { name: "Svalbard and Jan Mayen", iso: "SJ", phoneCode: "+47" },
  { name: "Swaziland", iso: "SZ", phoneCode: "+268" },
  { name: "Sweden", iso: "SE", phoneCode: "+46" },
  { name: "Switzerland", iso: "CH", phoneCode: "+41" },
  { name: "Syria", iso: "SY", phoneCode: "+963" },
  { name: "Taiwan", iso: "TW", phoneCode: "+886" },
  { name: "Tajikistan", iso: "TJ", phoneCode: "+992" },
  { name: "Tanzania", iso: "TZ", phoneCode: "+255" },
  { name: "Thailand", iso: "TH", phoneCode: "+66" },
  { name: "Togo", iso: "TG", phoneCode: "+228" },
  { name: "Tokelau", iso: "TK", phoneCode: "+690" },
  { name: "Tonga", iso: "TO", phoneCode: "+676" },
  { name: "Trinidad and Tobago", iso: "TT", phoneCode: "+1-868" },
  { name: "Tunisia", iso: "TN", phoneCode: "+216" },
  { name: "Turkey", iso: "TR", phoneCode: "+90" },
  { name: "Turkmenistan", iso: "TM", phoneCode: "+993" },
  { name: "Turks and Caicos Islands", iso: "TC", phoneCode: "+1-649" },
  { name: "Tuvalu", iso: "TV", phoneCode: "+688" },
  { name: "United Arab Emirates", iso: "AE", phoneCode: "+971" },
  { name: "Uganda", iso: "UG", phoneCode: "+256" },
  { name: "United Kingdom", iso: "GB", phoneCode: "+44" },
  { name: "Ukraine", iso: "UA", phoneCode: "+380" },
  { name: "Uruguay", iso: "UY", phoneCode: "+598" },
  { name: "United States", iso: "US", phoneCode: "+1" },
  { name: "Uzbekistan", iso: "UZ", phoneCode: "+998" },
  { name: "Vanuatu", iso: "VU", phoneCode: "+678" },
  { name: "Vatican", iso: "VA", phoneCode: "+379" },
  { name: "Venezuela", iso: "VE", phoneCode: "+58" },
  { name: "Vietnam", iso: "VN", phoneCode: "+84" },
  { name: "U.S. Virgin Islands", iso: "VI", phoneCode: "+1-340" },
  { name: "Wallis and Futuna", iso: "WF", phoneCode: "+681" },
  { name: "Western Sahara", iso: "EH", phoneCode: "+212" },
  { name: "Yemen", iso: "YE", phoneCode: "+967" },
  { name: "Zambia", iso: "ZM", phoneCode: "+260" },
  { name: "Zimbabwe", iso: "ZW", phoneCode: "+263" }
];

// Helper function to get country by phone code
export const getCountryByPhoneCode = (phoneCode: string): CountryData | undefined => {
  return countries.find(country => country.phoneCode === phoneCode);
};

// Helper function to get country by ISO code
export const getCountryByISO = (iso: string): CountryData | undefined => {
  return countries.find(country => country.iso === iso.toUpperCase());
};

// Helper function to format phone number
export const formatPhoneNumber = (countryCode: string, areaCode: string, phoneNumber: string): string => {
  return `${countryCode} ${areaCode} ${phoneNumber}`.trim();
};

// Helper function to parse phone number
export const parsePhoneNumber = (fullPhone: string): { countryCode: string; areaCode: string; phoneNumber: string } => {
  const parts = fullPhone.split(' ');
  if (parts.length >= 3) {
    return {
      countryCode: parts[0],
      areaCode: parts[1],
      phoneNumber: parts.slice(2).join(' ')
    };
  } else if (parts.length === 2) {
    return {
      countryCode: parts[0],
      areaCode: '',
      phoneNumber: parts[1]
    };
  } else {
    return {
      countryCode: '',
      areaCode: '',
      phoneNumber: fullPhone
    };
  }
}; 